# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/asus/debx/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/asus/debx

PRODUCT_COPY_FILES += \
    vendor/asus/debx/proprietary/vendor/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-qmi-1.so \
    vendor/asus/debx/proprietary/vendor/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qcril-hook-oem.so
